---
- name: Deploy resources via Terraform
  hosts: localhost
  tasks:
    - name: Create EC2 instance with Terraform
      cloud.terraform.terraform:
        project_path: ../terraform/
        state: present
        force_init: true
        backend_config_files:
          - "{{ lookup('ansible.builtin.env', 'TF_BACKEND_CONFIG_FILE') }}"
