---
- name: Install and configure Apache HTTP Server
  hosts: all
  become: yes

  tasks:
    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Ensure httpd is running and enabled
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    - name: Create index.html with custom content
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "{{ message | default('Hello World') }}"
        owner: root
        group: root
        mode: '0644'

    - name: Checking of Apache Web Server runs
      uri:
        url: http://{{ inventory_hostname }}
      register: http_test

    - debug:
        msg: "You can now try to connect to http://{{ inventory_hostname }}"
      when: http_test.status == 200