---
- name: Install and configure Apache HTTP Server on any Linux distribution
  hosts: all
  become: yes
  # needed for OS distribution
  gather_facts: true

  tasks:
    - name: Amazon Linux
      block:
      - name: Install httpd on Amazon Linux
        ansible.builtin.yum:
          name: httpd
          state: present

      - name: Ensure apache2 is running and enabled
        ansible.builtin.service:
          name: httpd
          state: started
          enabled: yes
      when: ansible_facts['distribution'] == 'Amazon'


    - name: CentOS Linux
      block:
      - name: Install httpd package on CentOS
        ansible.builtin.dnf:
          name: httpd
          state: present

      - name: Ensure httpd is running and enabled
        ansible.builtin.service:
          name: httpd
          state: started
          enabled: yes
      when: ansible_facts['distribution'] == 'CentOS'


    - name: Create index.html with custom content
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "{{ message | default('Hello World') }}<br/><br/>Provided to you by {{ ansible_facts['distribution'] }} Linux" 
        owner: root
        group: root
        mode: '0644'

    - name: Test if Apache Web Server runs
      uri:
        url: http://{{ inventory_hostname }}
      register: http_test

    - name: It does!
      debug:
        msg: "You can now try to connect to http://{{ inventory_hostname }}"
      when: http_test.status == 200
